openapi: 3.0.0
servers: 
  - description: ServidorLocal
    url: http://localhost:3001
  
info:
  title: Delilah Resto
  version: 1.0.0
  description: API para pedidos de comida deliciosa. Como cliente, podés registrarte, ver el listado de nuestros productos y hacer una orden. Los administradores del restaurante tienen la posibilidad de recibir pedidos y actualizarlos.

tags:
- name: productos
  description: Todo sobre nuestros productos
- name: pedidos
  description: Acceso a los pedidos de clientes
- name: usuario
  description: Operaciones sobre los clientes

paths:
  /productos:
    get:
      tags:
      - productos
      summary: Ver listado de productos del menú
      operationId: verProductos
      responses:
        '200':
          description: Lista de productos traídos exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:  
                  $ref: '#/components/schemas/Productos'
        '404':
          description: Error 404. Lista de productos no encontrada.
    post:
      tags:
      - productos
      summary: Agregar un nuevo producto al menú
      operationId: agregarProducto
      requestBody:
        required: true
        content:
          multipart/mixed:
            schema:
              $ref: '#/components/schemas/Producto'
            encoding:
              imagen:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: Producto agregado exitosamente.
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Producto'
        '400':
          description: El producto ingresado ya existe, intentá con otro.
        '400':
          description: Error 400. Intente nuevamente.
  /productos/{productoId}:
    get:
      tags:
      - productos
      summary: Ver un producto por su Id
      operationId: verProductoId
      parameters: 
      - in: path
        name: productoId
        schema:
          type: integer
        description: ID del producto a buscar
        required: true
      responses:
        '200':
          description: Producto traído exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Error 404. Producto no encontrado
        '400':
          description: Error 400. Intente nuevamente
    put:
      tags:
      - productos
      summary: Editar un producto por su ID
      operationId: modificarProducto
      parameters: 
      - in: path
        name: productoId
        required: true
        content:
          multipart/mixed:
            schema:
              $ref: '#/components/schemas/Producto'
            encoding:
              imagen:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '404':
          description: Error 404. El producto ingresado no existe. No se actualizó ningun producto
        '400':
          description: Error 400. Intente nuevamente
    delete:
      tags:
      - productos
      summary: Elimina un producto por su ID
      operationId: eliminarProducto
      parameters:
      - in: path
        name: productoId
        schema:
          type: object
          properties:
            id_producto:
              type: integer
        required: true
        description: Producto a eliminarse
      responses:
        '200':
          description: Producto eliminado exitosamente
        '404':
          description: Error 404. El producto ingresado no existe. No se actualizó ningun producto
        '400':
          description: Error 400. Intente nuevamente
  /usuarios:
    get:
      tags:
      - usuario
      summary: Ver listado de usuarios
      operationId: verUsuarios
      responses:
        '200':
          description: Usuarios traídos exitosamente
          content:
            application/json:
              schema:
                type: array
                items:  
                  $ref: '#/components/schemas/Usuarios'
        '404':
          description: Error 404. Lista de usuarios no encontrada
  /usuario/signup:
    post:
      tags:
      - usuario
      summary: Registro del usuario en el sistema
      operationId: nuevoUsuario
      requestBody:
        required: true
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '400':
          description: Error 400. Usuario no creado
  /usuario/login:
    post:
      tags:
      - usuario
      summary: Logueo del usuario al sistema
      operationId: "logInUsuario"
      requestBody:
        required: true
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/UsuarioLogin'
      responses:
        "200":
          description: Usuario logueado exitosamente
        "400":
          description: Error 400. Intente nuevamente
        "400":
          descripcion: La contraseña ingresada es incorrecta. Intentá otra vez
        "404":
          description: Error 404. El usuario ingresado no existe, intentá con otro o registrate para acceder
  /pedidos:
    get:
      tags:
      - pedidos
      summary: Ver listado de pedidos
      operationId: verPedidos
      responses:
        '200':
          description: Pedidos traídos exitosamente
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Pedidos'
        '404':
          description: Error 404. Lista de pedidos no encontrada
        '400':
          description: Error 400. Intente nuevamente
    post:
      tags:
      - pedidos
      summary: Agregar un nuevo pedido
      operationId: crearPedido
      requestBody:
        required: true
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/PedidoNuevo'
      responses:
        '200':
          description: Pedido creado exitosamente
        '400':
          description: Error 400. Pedido no creado
  /pedidos/{pedidoId}:
    get:
      tags:
      - pedidos
      summary: Ver un pedido por su Id
      operationId: verPedidoId
      parameters: 
      - in: path
        name: pedidoId
        schema:
          type: integer
        description: ID del pedido a buscar
        required: true
      responses:
        '200':
          description: Pedido traído exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pedido'
        '404':
          description: Error 404. Pedido no encontrado
        '400':
          description: Error 400. Intente nuevamente
    put:
      tags:
      - pedidos
      summary: Modificar estado del pedido
      operationId: modificarPedido
      parameters: 
      - in: path
        name: pedidoId
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PedidoEstado'
      responses:
        '200':
          description: Estado del pedido actualizado exitosamente
        '404':
          description: Error 404. Pedido no encontrado
        '400':
          description: Error 400. Intente nuevamente
    delete:
      tags:
      - pedidos
      summary: Elimina un pedido por ID
      operationId: eliminarPedido
      parameters:
      - in: path
        name: pedidoId
        schema:
          type: object
          properties:
            id_pedido:
              type: integer
        required: true
        description: Pedido a eliminarse
      responses:
        '200':
          description: Pedido eliminado exitosamente
        '404':
          description: Error 404. Pedido no encontrado
        '400':
          description: Error 400. Intente nuevamente
  
components:
  schemas:
    Productos:
      type: object
      properties:
        id_producto:
          type: integer
          description: ID del producto
          example: 4
        nombre: 
          type: string
          description: Nombre del producto
          example: 'Sandwich de lomito'
        precio:
          type: number
          description: Precio del producto
          example: 420
        descripcion:
          type: string
          description: Descripción corta del producto
          example: 'Sandwich de lomito a la parrilla con queso'
        imagen:
          type: string
          format: binary
    Producto:
      type: object
      properties:
        nombre: 
          type: string
          description: Nombre del producto
          example: 'Sandwich de lomito'
        precio:
          type: number
          description: Precio del producto
          example: 420
        descripcion:
          type: string
          description: Descripción corta del producto
          example: 'Sandwich de lomito a la parrilla con queso'
        imagen:
          type: string
          format: binary
    Usuarios:
      type: object
      properties:
        id_usuario:
          type: integer
          description: ID del usuario
          example: 5
        usuario: 
          type: string
          description: Usuario
          example: 'queen_freddie'
        nombre_apellido: 
          type: string
          description: Nombre y apellido del usuario
          example: 'Freddie Mercury'
        email: 
          type: string
          description: Mail del usuario
          example: 'freddie@gmail.com'
        telefono:
          type: integer
          description: Teléfono del usuario
          example: 541144444444
        direccion_envio:
          type: string
          description: Dirección de envío del usuario
          example: 'Calle de freddie mercury, londres, uk'
        pw:
          type: string
          description: Contraseña del usuario
          example: '1lovemyc4ts'
        admin:
            type: integer
            description: Rol del usuario
            example: 2
    Usuario:
      type: object
      properties:
        usuario: 
          type: string
          description: Usuario
          example: 'queen_freddie'
        nombre_apellido: 
          type: string
          description: Nombre y apellido del usuario
          example: 'Freddie Mercury'
        email: 
          type: string
          description: Mail del usuario
          example: 'freddie@gmail.com'
        telefono:
          type: integer
          description: Teléfono del usuario
          example: 54 11 4444 4444
        direccion_envio:
          type: string
          description: Dirección de envío del usuario
          example: 'Calle de freddie mercury, londres, uk'
        pw:
          type: string
          description: Contraseña del usuario
          example: '1lovemyc4ts'
    UsuarioLogin:
      type: object
      properties:
        usuario: 
          type: string
          description: Usuario o email
          example: 'queen_freddie'
        pw:
          type: string
          description: Contraseña del usuario
          example: '1lovemyc4ts'
    Pedidos:
      type: object
      properties:
        id_pedido:
          type: integer
          description: ID del pedido
          example: 5
        fecha_pedido:
          type: date
          description: fecha y hora del pedido
          example: 2020-11-15T23:23:08.000Z
        estado:
          type: string
          description: Estado actual del producto
          enum:
            - nuevo
            - confirmado
            - preparando
            - enviando
            - entregado
            - cancelado
          example: 'nuevo'
        tipo_pago:
          type: string
          description: Tipo de pago elegido para el pedido
          enum:
            - efectivo
            - tarjeta de credito/debito
          example: 'efectivo'
        nombre:
          type: string
          description: Nombre del producto elegido
          example: 'Sandwich de lomito'
        cantidad_producto:
          type: integer
          description: cantidad pedida del producto
          example: 2
        precio:
          type: number
          description: Precio del producto elegido
          example: 420
        subtotal:
          type: number
          description: Subtotal del producto * cantidades elegidas
          example: 840
        usuario:
          type: string
          description: Usuario que realizo el pedido
          example: 'queen_freddie'
        nombre_apellido:
          type: string
          description: Nombre y apellido del usuario que realizo el pedido
          example: 'Freddie Mercury'
        direccion_envio:
          type: string
          description: Dirección de envío del usuario que realizo el pedido
          example: 'Calle de freddie mercury, londres, uk'
        email:
          type: string
          description: Mail del usuario que realizo el pedido
          example: 'freddie@gmail.com'
    Pedido:
      type: object
      properties:
        id_pedido:
          type: integer
          description: ID del pedido
          example: 5
        estado:
          type: string
          description: Estado actual del producto
          enum:
            - nuevo
            - confirmado
            - preparando
            - enviando
            - entregado
            - cancelado
          example: 'nuevo'
        nombre:
          type: string
          description: Nombre del producto elegido
          example: 'Sandwich de lomito'
        cantidad_producto:
          type: integer
          description: cantidad pedida del producto
          example: 2
        precio:
          type: number
          description: Precio del producto elegido
          example: 420
        subtotal:
          type: number
          description: Subtotal del producto * cantidades elegidas
          example: 840
    PedidoNuevo:
      type: object
      properties:
        id_pago:
          type: integer
          description: Tipo de pago elegido
          default: 1
        productos: 
          type: array
          description: Array de productos encargados
          items:
            properties:
              id_producto: 
                type: integer
                description: Id del pedido
                example: 1
              cantidad_producto: 
                type: integer
                description: cantidad del producto pedido
                example: 2
    PedidoEstado:
      type: object
      properties:
        estado_nuevo:
          type: integer
          description: ID del estado nuevo
          example: 2

externalDocs:
  description: Explorá la API acá
  url: https://github.com/antobayugar/delilah_resto